from playwright.sync_api import Page


def test_fill_form(page: Page):
    page.goto('https://demoqa.com/automation-practice-form')
    input_text_first = page.locator('#firstName')
    input_text_first.fill('Ivan')
    input_text_last = page.locator('#lastName')
    input_text_last.fill('Smirnov')
    input_text_email = page.locator('#userEmail')
    input_text_email.fill('name123@example.com')
    page.locator('#gender-radio-1').click(force=True)
    input_text_phone = page.locator('#userNumber')
    input_text_phone.fill('1234567890')
    input_subject = page.locator('#subjectsContainer')
    input_subject.click()
    input_subject = page.locator('#subjectsInput')
    input_subject.fill('English')
    input_subject.press('Enter')
    input_text_birth = page.locator('#dateOfBirthInput')
    input_text_birth.click()
    input_text_birth.press('Control+a')
    input_text_birth.fill('01 Feb 2000')
    input_text_birth.press('Enter')
    page.locator('text=Sports').click()
    input_address = page.locator('#currentAddress')
    input_address.fill('Address 123')
    select_state = page.locator('#state')
    select_state.click()
    select_state = page.locator('#react-select-3-input')
    select_state.fill('Haryana')
    select_state.press('Enter')
    select_city = page.locator('#city')
    select_city.click()
    select_city = page.locator('#react-select-4-input')
    select_city.fill('Karnal')
    select_city.press('Enter')
    submit = page.locator('#submit')
    submit.click()
